---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'future-imperfect'
Debug:
  friendly_error_httpcode: true
SiteConfig:
  extensions:
    - SiteConfigExtension
BlogPost:
  extensions:
    - BlogPostExtension
SiteTree:
  extensions:
    - CommentsExtension
  comments:
    require_moderation_cms: true
Comment:
  extensions:
    - CommentExtension
