---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\View\SSViewer:
  theme: 'future-imperfect'
SilverStripe\Dev\Debug:
  friendly_error_httpcode: true
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - BlogPostExtension
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    require_moderation_cms: true
    use_gravatar: true
    gravatar_default: 'identicon'
    gravatar_rating: 'pg'
SilverStripe\Comments\Controllers\CommentingController:
  extensions:
    - CommentExtension
